//go:build ignore

package main

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"os"
)

func main() {
	const size = 32
	img := image.NewNRGBA(image.Rect(0, 0, size, size))

	// Colors
	bg := color.NRGBA{0, 0, 0, 0}
	white := color.NRGBA{230, 230, 230, 255}
	outline := color.NRGBA{40, 40, 40, 255}
	eyeColor := color.NRGBA{200, 30, 30, 255}

	// Fill transparent
	for y := 0; y < size; y++ {
		for x := 0; x < size; x++ {
			img.SetNRGBA(x, y, bg)
		}
	}

	// Helper to draw filled ellipse
	fillEllipse := func(cx, cy, rx, ry int, c color.NRGBA) {
		for y := cy - ry; y <= cy+ry; y++ {
			for x := cx - rx; x <= cx+rx; x++ {
				dx := float64(x-cx) / float64(rx)
				dy := float64(y-cy) / float64(ry)
				if dx*dx+dy*dy <= 1.0 {
					if x >= 0 && x < size && y >= 0 && y < size {
						img.SetNRGBA(x, y, c)
					}
				}
			}
		}
	}

	// Skull cranium - outline then fill
	fillEllipse(16, 13, 13, 11, outline)
	fillEllipse(16, 13, 11, 9, white)

	// Jaw - outline then fill
	fillEllipse(16, 22, 8, 6, outline)
	fillEllipse(16, 22, 6, 4, white)

	// Merge cranium and jaw
	for y := 16; y <= 20; y++ {
		for x := 8; x <= 24; x++ {
			dx := float64(x-16) / 11.0
			if dx*dx <= 1.0 {
				img.SetNRGBA(x, y, white)
			}
		}
	}
	// Side outlines for connection
	for y := 16; y <= 20; y++ {
		img.SetNRGBA(7, y, outline)
		img.SetNRGBA(8, y, outline)
		img.SetNRGBA(24, y, outline)
		img.SetNRGBA(25, y, outline)
	}

	// Left eye
	fillEllipse(12, 12, 4, 3, outline)
	fillEllipse(12, 12, 3, 2, eyeColor)

	// Right eye
	fillEllipse(20, 12, 4, 3, outline)
	fillEllipse(20, 12, 3, 2, eyeColor)

	// Nose
	img.SetNRGBA(15, 17, outline)
	img.SetNRGBA(16, 17, outline)
	img.SetNRGBA(17, 17, outline)
	img.SetNRGBA(15, 18, outline)
	img.SetNRGBA(17, 18, outline)

	// Teeth lines
	for y := 23; y <= 26; y++ {
		img.SetNRGBA(13, y, outline)
		img.SetNRGBA(16, y, outline)
		img.SetNRGBA(19, y, outline)
	}
	// Teeth top line
	for x := 12; x <= 20; x++ {
		img.SetNRGBA(x, 23, outline)
	}

	// Encode as PNG first (for preview)
	var pngBuf bytes.Buffer
	if err := png.Encode(&pngBuf, img); err != nil {
		fmt.Fprintf(os.Stderr, "png encode error: %v\n", err)
		os.Exit(1)
	}
	os.WriteFile("icon_preview.png", pngBuf.Bytes(), 0644)

	// Encode as ICO (Windows icon format)
	icoBytes := encodeICO(img)

	// Write Go source with byte literal
	var src bytes.Buffer
	src.WriteString("// Code generated by cmd/icongen; DO NOT EDIT.\n\n")
	src.WriteString("package tray\n\n")
	src.WriteString("// iconData is a 32x32 ICO skull icon with red eyes and transparent background.\n")
	src.WriteString("var iconData = []byte{")
	for i, by := range icoBytes {
		if i%16 == 0 {
			src.WriteString("\n\t")
		}
		fmt.Fprintf(&src, "0x%02X, ", by)
	}
	src.WriteString("\n}\n")

	if err := os.WriteFile("internal/tray/icon_data.go", src.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write go error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated ICO icon: %d bytes\n", len(icoBytes))
	fmt.Println("Written: icon_preview.png (for visual check)")
	fmt.Println("Written: internal/tray/icon_data.go")
}

// encodeICO encodes an NRGBA image as a Windows ICO file with a single PNG-compressed entry.
func encodeICO(img *image.NRGBA) []byte {
	bounds := img.Bounds()
	w := bounds.Dx()
	h := bounds.Dy()

	// Encode the image as PNG for the ICO entry
	var pngBuf bytes.Buffer
	png.Encode(&pngBuf, img)
	pngData := pngBuf.Bytes()

	// ICO header: 6 bytes
	// ICO dir entry: 16 bytes
	// PNG data follows
	headerSize := 6
	dirEntrySize := 16
	dataOffset := headerSize + dirEntrySize

	var buf bytes.Buffer

	// ICONDIR header
	binary.Write(&buf, binary.LittleEndian, uint16(0))    // reserved
	binary.Write(&buf, binary.LittleEndian, uint16(1))    // type: 1 = ICO
	binary.Write(&buf, binary.LittleEndian, uint16(1))    // count: 1 image

	// ICONDIRENTRY
	icoW := byte(w)
	icoH := byte(h)
	if w == 256 {
		icoW = 0
	}
	if h == 256 {
		icoH = 0
	}
	buf.WriteByte(icoW)                                                   // width
	buf.WriteByte(icoH)                                                   // height
	buf.WriteByte(0)                                                      // color palette count
	buf.WriteByte(0)                                                      // reserved
	binary.Write(&buf, binary.LittleEndian, uint16(1))                    // color planes
	binary.Write(&buf, binary.LittleEndian, uint16(32))                   // bits per pixel
	binary.Write(&buf, binary.LittleEndian, uint32(len(pngData)))         // image size
	binary.Write(&buf, binary.LittleEndian, uint32(dataOffset))           // data offset

	// PNG data
	buf.Write(pngData)

	return buf.Bytes()
}
